### ISSUE TITLE
use of python

### ISSUE THREAD

**Issue by haraldh** [intel/thunderbolt-software-user-space#19]
https://github.com/01org/thunderbolt-software-user-space/blob/875914be08fcc32d69ebe5579ec48915aa0e38e7/tbtacl/write.py#L1

Adding the complete python stack in the initramfs just to get errno from the write to a sysfs file is completely overkill.

Also udev rules shouldn't be that heavy-weight.

**Comment by ybernat** [comment]
First, thank for your feedback!

For the usage of python:
1. I don't think tbtacl belongs to initramfs. Is the ACL itself available in initramfs? Will the initrd be updated each time the user adds a new device to ACL?
1. For having TBT devices available on boot, a more holistic solution is needed anyway for having them available in preboot environment. If the user can't use the keyboard for BIOS setup and for grub (or whatever boot loader), the gain from approving the device before root FS is loaded seems negligible for me.
1. As you can see, the exact errno is important. Removing the incorrect key seems like the simplest and most straightforward way to signal GUI that the device needs user attention.

I'm not sure about the comment for udev rules. Would you please elaborate on this?

**Comment by haraldh** [comment]
> I'm not sure about the comment for udev rules. Would you please elaborate on this?

For the sake of portability and for systems without python, please turn your python program into a tiny C program. Thank you!

**Comment by haraldh** [comment]
ouch... C++ for a simple write.. you really don't like small lean helper tools

**Comment by ybernat** [comment]
I already created the C++ wrapper for the POSIX syscalls as I had to use them for `tbtadm` tool, so I just reused it.
We can go into language flame war about C vs. C++, if this is what you'd want us to go into ;-)

The final result is the same: this issue is resolved, as you don't need python anymore for `tbtacl` to work. C++ compilers are available virtually everywhere you want this code to run, as much as I know (and `tbtadm` is in C++ already).
