### ISSUE TITLE
Add colors to tbtadm output

### ISSUE THREAD

**Issue by westeri** [intel/thunderbolt-software-user-space#26]
Any modern command line tool has fancy colors, tbtadm should not be an exception.

**Comment by ybernat** [comment]
Any specific suggestion where color should be added?
I guess red for error messages, but what else?

**Comment by westeri** [comment]
I think for example `tbtadm acl` could show green/red dot if the device is connected and so on, like when you run `systemctl status gdm`. For `tbtadm topology` device/vendor name could be in different color and so on :)

**Comment by ybernat** [comment]
> I think for example tbtadm acl could show green/red dot if the device is connected

Makes sense, but probably not red for not connected, as red is signaling an error or problem, which isn't the case here. Maybe something more neutral like yellow (or just having the entries for connected devices in bold?).

> For tbtadm topology device/vendor name could be in different color

I prefer not. I don't think there is a point in adding a colors just because we can. The colors must help the readability of the information or give a strong clue to the user what the displayed information is even without reading it all, etc.

But now that I think about the output of `devices` and `topology` commands, it seems like a good idea to color the "connected" and "in ACL" information with green/yellow (or maybe red is a good fit here for the "not connected" case, as the device isn't functional in this case).

OK, nice suggestion. Thanks!
